feat(whatsApp_business): support for SMB
KnugiHK/WhatsApp-Chat-Exporter pull request #60
Opened 2023-08-15 04:48 UTC by andrp92

2023-08-15 04:53 UTC, andrp92 commented
Hello there, @KnugiHK!

I've come across a truly fascinating project—kudos to you! Recently, I encountered a situation where I needed to create a local backup of my WhatsApp business account. Upon exploring the project, I discovered that it didn't quite support this functionality out of the box. However, I took the initiative to tweak a few elements, and voilà, it's now functioning seamlessly.

Feeling quite satisfied with the results, I've decided to take things a step further and collaborate with you on this. I've already initiated a pull request. If there are any suggestions or adjustments you'd like me to implement, please don't hesitate to share. I'm more than willing to lend a hand and make this project even better. Looking forward to working together!

2023-08-15 05:05 UTC, andrp92 commented
Btw, I don't have myself an Android device so I didn't even attempt to implement this for Android. I might need a little help there.

2023-08-15 06:16 UTC, KnugiHK requested changes
The commit to vcard could break Android's vcard output. I will fix it and consolidate the changes.

2023-08-15 06:16 UTC, KnugiHK commented on Whatsapp_Chat_Exporter/__main__.py
> +                vcard(db, data, args.media)
This could break Android's vcard output.

2023-08-15 09:42 UTC, KnugiHK commented on Whatsapp_Chat_Exporter/__main__.py
> +                vcard(db, data, args.media)
Should be fixed now.

2023-08-15 09:47 UTC, KnugiHK requested changes
One outstanding problem for encrypted iOS backup. See the comment in `extract_iphone_media.py`.

2023-08-15 09:47 UTC, KnugiHK commented on Whatsapp_Chat_Exporter/extract_iphone_media.py
If the iOS backup is encrypted, the extract_encrypted function will either raise an error or extract files for the non-business version of WhatsApp.

Can you figure out the file name of the message and the contact databases' filename?

2023-08-15 09:50 UTC, KnugiHK commented
Although the PR does not works for encrypted backup, unencrypted backup should be fine.

I refactored the code a bit. Try again to see if it works for WhatsApp Business in iOS.

2023-08-15 12:54 UTC, andrp92 commented on Whatsapp_Chat_Exporter/extract_iphone_media.py
Sure. I will check this out as soon as I can.

2023-08-15 12:58 UTC, andrp92 commented
@KnugiHK Loved the way you implemented identifiers. It's a lot cleaner and easier to maintain that way 🙌

2023-08-18 05:54 UTC, andrp92 commented on Whatsapp_Chat_Exporter/extract_iphone_media.py
I can confirm that file names stay the same for both, business and regular WhatsApp on both, encrypted and unencrypted backups. Also, I can confirm that changes made are working properly. 

I submitted a commit to use dynamic domain also for encrypted backups.

![Screenshot 2023-08-18 at 1 15 49 AM](https://github.com/KnugiHK/WhatsApp-Chat-Exporter/assets/28060986/cc5d0c00-2361-4e51-9151-48d7a08be8ed)

2023-08-18 05:57 UTC, KnugiHK commented on Whatsapp_Chat_Exporter/extract_iphone_media.py
I see. Thanks for your confirmation. However, I am wondering if I have both WhatsApp and WhatsApp Business installed, will it be able to extract the correct one?

2023-08-18 05:59 UTC, andrp92 commented on Whatsapp_Chat_Exporter/extract_iphone_media.py
I will be testing that out today (later, its 2:00 AM in DR), and I will let you know.

2023-08-18 06:00 UTC, KnugiHK commented on Whatsapp_Chat_Exporter/extract_iphone_media.py
Take your time!

2023-08-18 06:01 UTC, andrp92 commented on Whatsapp_Chat_Exporter/extract_iphone_media.py
However, just giving it a quick thought, as longs as the arg (--business) correspond to the desired app it should work. Since the domain will vary based on that.

2023-08-18 06:04 UTC, andrp92 commented on Whatsapp_Chat_Exporter/extract_iphone_media.py
Found something very interesting (a bug, maybe?), when you have Whatsapp and migrate to Whatsapp business or the opposite, some records will lose its ids and python doesn't like it [here](https://github.com/KnugiHK/WhatsApp-Chat-Exporter/blob/main/Whatsapp_Chat_Exporter/extract_iphone.py#L93) . I don't see any relation to the changes we have made. Maybe I will test it with the main branch tomorrow to see if behavior is the same.

2023-08-18 06:07 UTC, andrp92 commented on Whatsapp_Chat_Exporter/extract_iphone_media.py
`Traceback (most recent call last):65)
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/runpy.py", line 198, in _run_module_as_main
    return _run_code(code, main_globals, None,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/runpy.py", line 88, in _run_code
    exec(code, run_globals)
  File "/.vscode/extensions/ms-python.python-2023.14.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/.vscode/extensions/ms-python.python-2023.14.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/.vscode/extensions/ms-python.python-2023.14.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/.vscode/extensions/ms-python.python-2023.14.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.vscode/extensions/ms-python.python-2023.14.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/.vscode/extensions/ms-python.python-2023.14.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/WhatsApp-Chat-Exporter/Whatsapp_Chat_Exporter/__main__.py", line 382, in <module>
    main()
  File "/Whatsapp_Chat_Exporter/__main__.py", line 305, in main
    messages(db, data, args.media)
  File "/dev/itunes-backup/.venv/lib/python3.11/site-packages/Whatsapp_Chat_Exporter/extract_iphone.py", line 93, in messages
    path = f'{media_folder}/Media/Profile/{_id.split("@")[0]}'
                                           ^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'split'`

2023-08-18 06:08 UTC, KnugiHK commented on Whatsapp_Chat_Exporter/extract_iphone_media.py
> However, just giving it a quick thought, as longs as the arg (--business) correspond to the desired app it should work. Since the domain will vary based on that.

I am not so sure about that. Given the logic in `extract_encrypted()` does not account for the domain when extracting the chat and the contact db but relies on the relative_path solely. If they have the same file name, they may conflict to each other?
`extract_iphone_media.py` line 23-26
```python
        backup.extract_file(relative_path=RelativePath.WHATSAPP_MESSAGES,
                        output_filename=identifiers.MESSAGE)
        backup.extract_file(relative_path=RelativePath.WHATSAPP_CONTACTS,
                            output_filename=identifiers.CONTACT)
```

2023-08-18 06:13 UTC, KnugiHK commented on Whatsapp_Chat_Exporter/extract_iphone_media.py
> Found something very interesting (a bug, maybe?), when you have Whatsapp and migrate to Whatsapp business or the opposite, some records will lose its ids and python doesn't like it [here](https://github.com/KnugiHK/WhatsApp-Chat-Exporter/blob/main/Whatsapp_Chat_Exporter/extract_iphone.py#L93) . I don't see any relation to the changes we have made. Maybe I will test it with the main branch tomorrow to see if behavior is the same.
> 


It seems to be a bug. The `_id` is essential to identify which chat the message belongs to. If more than two messages that belong to two chats have the `None` id, it may crash not only in the line you mentioned but in some other places. Therefore, please open another issue for better tracking of the problem. Thanks.

2023-08-18 06:14 UTC, andrp92 commented on Whatsapp_Chat_Exporter/extract_iphone_media.py
**iphone_backup.py** line 29-30:     
    `WHATSAPP_MESSAGES = "ChatStorage.sqlite"
    WHATSAPP_CONTACTS = "ContactsV2.sqlite"`
    
Path are equal for both, enterprise and regular Whatsapp. 

Whatsapp:
![Screenshot 2023-08-18 at 2 13 59 AM](https://github.com/KnugiHK/WhatsApp-Chat-Exporter/assets/28060986/14cb6142-976c-403b-9427-2cdf6978393f)

Whatsapp Business:
![Screenshot 2023-08-18 at 2 13 45 AM](https://github.com/KnugiHK/WhatsApp-Chat-Exporter/assets/28060986/89cf3aae-c070-4bbf-ae42-6568369dc1a3)

2023-08-18 06:18 UTC, andrp92 commented on Whatsapp_Chat_Exporter/extract_iphone_media.py
I am certainly a little concern too, so I will be looking into that.

2023-08-18 06:27 UTC, andrp92 commented on Whatsapp_Chat_Exporter/extract_iphone_media.py
@KnugiHK maybe we can use this [function](https://github.com/KnugiHK/iphone_backup_decrypt/blob/master/src/iphone_backup_decrypt/iphone_backup.py#L269) instead. So we can prove a whole domain instead of a relative path.

2023-08-22 13:38 UTC, andrp92 commented on Whatsapp_Chat_Exporter/extract_iphone_media.py
Hey @KnugiHK , have you had the chance to check this comment? 

> @KnugiHK maybe we can use this [function](https://github.com/KnugiHK/iphone_backup_decrypt/blob/master/src/iphone_backup_decrypt/iphone_backup.py#L269) instead. So we can provide a whole domain instead of a relative path.

2023-08-22 15:18 UTC, KnugiHK commented on Whatsapp_Chat_Exporter/extract_iphone_media.py
Oh. I wrote a comment and didn't send that out.

The function you mentioned is already used in the latter [lines](https://github.com/KnugiHK/WhatsApp-Chat-Exporter/blob/736292538bb0961092793c5623b842d067738649/Whatsapp_Chat_Exporter/extract_iphone_media.py#L30C23-L30C46). We only need two specific files in the lines we are concerned about and `extract_files` function is used to extract everything with a particular domain or relative path, which is not what we want. It is preferable to modify the `extract_file` function just like this [commit](https://github.com/KnugiHK/iphone_backup_decrypt/commit/404ce3378c9207856cdda989edaefe307d396b51). I will fix the problem later.

2023-08-22 19:04 UTC, andrp92 commented on Whatsapp_Chat_Exporter/extract_iphone_media.py
> Oh. I wrote a comment and didn't send that out.
> 
> The function you mentioned is already used in the latter [lines](https://github.com/KnugiHK/WhatsApp-Chat-Exporter/blob/736292538bb0961092793c5623b842d067738649/Whatsapp_Chat_Exporter/extract_iphone_media.py#L30C23-L30C46). We only need two specific files in the lines we are concerned about and `extract_files` function is used to extract everything with a particular domain or relative path, which is not what we want. It is preferable to modify the `extract_file` function just like this [commit](https://github.com/KnugiHK/iphone_backup_decrypt/commit/404ce3378c9207856cdda989edaefe307d396b51). I will fix the problem later.

Been there done that, jeje. Alright. If there is anything I can help with, please let me know. Regards,

2023-08-23 08:11 UTC, KnugiHK commented on Whatsapp_Chat_Exporter/extract_iphone_media.py
Pushed the fix to the PR. You can see if it solves the problem or if any bug is introduced. Make sure to install the latest version of [iphone_backup_decrypt](https://github.com/KnugiHK/iphone_backup_decrypt/commit/c47df99d7ecacbeccec2ddf5fd7615f3275f6dd0). Thanks!

2023-08-23 22:40 UTC, andrp92 commented on Whatsapp_Chat_Exporter/extract_iphone_media.py
Alright. Will test it out as soon as I can 💪

2023-09-11 22:35 UTC, andrp92 commented
@KnugiHK it did work as expected 🚀. However, there's a weird WhatsApp message that I hadn't seen before:
![Screenshot 2023-09-11 at 6 30 32 PM](https://github.com/KnugiHK/WhatsApp-Chat-Exporter/assets/28060986/0cb9e038-9973-4529-9c53-f961f04b44c9)

2023-09-14 11:54 UTC, andrp92 commented on Whatsapp_Chat_Exporter/extract_iphone_media.py
It does solve the bug and works as expected.

2023-09-16 02:40 UTC, KnugiHK commented
> @KnugiHK it did work as expected 🚀. However, there's a weird WhatsApp message that I hadn't seen before: 

Can you check what that message is in WhatsApp?

2023-09-16 07:12 UTC, andrp92 commented
> > @KnugiHK it did work as expected 🚀. However, there's a weird WhatsApp message that I hadn't seen before:
> 
> Can you check what that message is in WhatsApp?

Those are old messages that seems to have corrupted when migrating from android version of WB with a third party application. I can confirm that new messages (generated on the iPhone) are intact and showing correctly.

2023-09-16 09:06 UTC, KnugiHK commented
> > > @KnugiHK it did work as expected 🚀. However, there's a weird WhatsApp message that I hadn't seen before:
> > 
> > 
> > Can you check what that message is in WhatsApp?
> 
> Those are old messages that seems to have corrupted when I migrated from android version of WB with a third party application long time ago. New messages (generated on the iPhone) are intact and showing correctly.

Shall we consider it as not related to this PR?

2023-09-17 23:44 UTC, andrp92 commented
> > > > @KnugiHK it did work as expected 🚀. However, there's a weird WhatsApp message that I hadn't seen before:
> > > 
> > > 
> > > Can you check what that message is in WhatsApp?
> > 
> > 
> > Those are old messages that seems to have corrupted when I migrated from android version of WB with a third party application long time ago. New messages (generated on the iPhone) are intact and showing correctly.
> 
> Shall we consider it as not related to this PR?

Not at all. That's a corner case that's outside of this module scope.

2023-09-17 23:51 UTC, KnugiHK commented
Great. Will merge it soon.

2023-09-22 13:33 UTC, merged

2023-09-22 13:54 UTC, KnugiHK commented
Thanks for your contribution!

2023-09-22 13:55 UTC, KnugiHK reviewed
LGTM

2023-11-12 06:51 UTC, KnugiHK commented
Released in [0.9.7](https://github.com/KnugiHK/WhatsApp-Chat-Exporter/releases/tag/0.9.7).